---
name: Setup
description: Setup Ruby and install dependencies.

inputs:
  ruby_version:
    description: The Ruby version.
    required: false
    default: '3.2.0'
  install_dependencies:
    description: Install dependencies.
    type: boolean
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: ${{ inputs.install_dependencies }}
        ruby-version: ${{ inputs.ruby_version }}
