---
name: Check

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          ruby_version: ${{ matrix.ruby }}
      - name: Test
        run: bundle exec rake test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          ruby_version: ${{ matrix.ruby }}
      - name: Lint
        run: bundle exec rake lint
