---

run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: bundle exec rake build
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          files: pkg/*
          fail_on_unmatched_files: true
          prerelease: ${{ contains(github.ref_name, 'pre') }}
  rubygems:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Setup credentials
        run: |
          mkdir -p ~/.gem
          echo ":rubygems: $TOKEN" > ~/.gem/credentials
          chmod 600 ~/.gem/credentials
        env:
          TOKEN: ${{ secrets.RUBYGEMS_API_KEY }}
      - name: Publish
        run: bundle exec gem release
        env:
          GEM_RELEASE_KEY: rubygems
          GEM_RELEASE_HOST: https://rubygems.org
  github:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Setup credentials
        run: |
          mkdir -p ~/.gem
          echo ":github: Bearer $TOKEN" > ~/.gem/credentials
          chmod 600 ~/.gem/credentials
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: bundle exec gem release
        env:
          GEM_RELEASE_KEY: github
          GEM_RELEASE_HOST: https://rubygems.pkg.github.com/${{ github.repository_owner }}
