---
name: Publish version

run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - v*

env:
  artifact_path: pkg

jobs:
  artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: bundle exec rake build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          if-no-files-found: error
          path: ${{ env.artifact_path }}/
  release:
    name: GitHub Releases
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}
          path: ${{ env.artifact_path }}/
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          fail_on_unmatched_files: true
          prerelease: ${{ contains(github.ref_name, 'pre') }}
          files: ${{ env.artifact_path }}/*
  rubygems:
    name: RubyGems.org
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          install_dependencies: false
          gem_credentials: ':rubygems: ${{ secrets.RUBYGEMS_API_KEY }}'
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}
          path: ${{ env.artifact_path }}/
      - name: Publish
        run: gem push --key $GEM_RELEASE_KEY --host $GEM_RELEASE_HOST $ARTIFACT_PATH/*
        env:
          GEM_RELEASE_KEY: rubygems
          GEM_RELEASE_HOST: https://rubygems.org
          ARTIFACT_PATH: ${{ env.artifact_path }}
  github:
    name: GitHub Packages
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write
    needs: artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          install_dependencies: false
          gem_credentials: ':github: Bearer ${{ secrets.GITHUB_TOKEN }}'
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}
          path: ${{ env.artifact_path }}/
      - name: Publish
        run: gem push --key $GEM_RELEASE_KEY --host $GEM_RELEASE_HOST $ARTIFACT_PATH/*
        env:
          GEM_RELEASE_KEY: github
          GEM_RELEASE_HOST: https://rubygems.pkg.github.com/${{ github.repository_owner }}
          ARTIFACT_PATH: ${{ env.artifact_path }}
