---
name: Publish version

run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - v*

env:
  artifact_path: pkg

jobs:
  artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: bundle exec rake build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          if-no-files-found: error
          path: ${{ env.artifact_path }}/
  release:
    name: GitHub Releases
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}
          path: ${{ env.artifact_path }}/
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          fail_on_unmatched_files: true
          prerelease: ${{ contains(github.ref_name, 'pre') }}
          files: ${{ env.artifact_path }}/*
  rubygems:
    name: RubyGems.org
    uses: ./.github/workflows/publish-gem.yml
    needs: artifacts
    with:
       registry_key: rubygems
       registry_host: https://rubygems.org
       gem_artifacts: pkg
    secrets:
       registry_credentials: ${{ secrets.RUBYGEMS_API_KEY }}
  github:
    name: GitHub Packages
    uses: ./.github/workflows/publish-gem.yml
    permissions:
      packages: write
    needs: artifacts
    with:
       registry_key: github
       registry_host: https://rubygems.pkg.github.com/${{ github.repository_owner }}
       gem_artifacts: pkg
    secrets:
       credentials: Bearer ${{ secrets.GITHUB_TOKEN }}
